defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *defaults
  database: mars_rovers

production:
  <<: *defaults
  database: mars_rovers

test:
  <<: *defaults
  database: mars_rovers_test
