# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bbc56c1f9e0f85ad3290a1bda9e2dca07366c0a8e989751c4eaea9b5fcdd7342f2d59a0dae1d7ff47d85fe4db7ffd2feb7b35df18bf7ffa5677d17302a2ca4a

test:
  secret_key_base: 0692d519a089c9b1d99062ec4f3c6abf3978b472d467325fabfb9c43f48afdb25e20a2549f84c6667fff8f3aff427a65c0c96a491a343c00fe480f8dfd8dc86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
